config/routes.rb
Rails.application.routes.draw do
  get '/reservations/:id/braintree/new' => "braintree#new" , as:"new_braintree"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create , :show , :edit , :update] do

    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

    resources :reservations, only: [:index]

  end
  resources :listings do
    resources :reservations
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'users#index'
  get 'users/secret'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/listings/:id/user_listings" => "listings#user_listings" , as: "user_listings"

  post '/listings/:id/verify' => "listings#verify", as: "verify_listing"
  post '/reservations/:id/checkout' => "braintree#checkout", as: "checkout"
  post '/listings/search' => "listings#search" , as:"search"
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :reservations , dependent: :destroy
  belongs_to :user
  mount_uploaders :images, ImagesUploader

  scope :text_search, -> (text) {
    text_with_wildcard = "%#{text}%"
    where("country ILIKE ? OR title_name ILIKE ? OR city ILIKE ? OR state ILIKE ? OR address ILIKE ?", text_with_wildcard, text_with_wildcard, text_with_wildcard, text_with_wildcard, text_with_wildcard)
  }

  scope :number, -> (number) { where('beds = ?' , number)}
  scope :number, -> (number) { where('beds = ?' , number)}

  # scope :min_max_price ->(min,max) { where('price > ? AND price < ?', min, max) }


  # scope :address, (address) -> { where("address ILIKE #{address}") }

  # def self.address(address)
  #   self.where("address ILIKE #{address}")
  # end


end

# Listing.text_search(params[:search])
# Listing.address('Blvd 3') # =>
# Listing.address(params(:search))

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  TAGS = ['tv', 'pool', 'kitchen', 'smoking']

  before_action :set_listing, only: [:edit , :show , :update , :destroy ]
  before_action :authorize_user , only: [:edit , :update , :destroy]
  before_action :moderator_user , only: [:verify]
  def index
    if params[:search]
      @listings = Listing.text_search(params[:search])
    elsif params[:number]

      @listings = Listing.number(params[:number])
      # elsif params[:min_max_price]
      #   @listings = Listing.min_max_price(params[:min_max_price])
    else

      @listings=Listing.all.order("address")

    end
    respond_to do |format|
      format.html
      format.js
      format.json { render json:@listings}
    end

  end
  def new

    @listing = Listing.new


  end

  def create
    @listing = Listing.new(listings_params)
    @listing.user_id=current_user.id

    tags = tags_params.to_h.map do |k,v|
      if v == "1"
        k
      end
    end

    @listing.tags = tags

    if @listing.save
      redirect_to listings_path
    else
      render 'new'
    end
  end
  def show
    @listings=Listing.all

    @listing=Listing.find(params[:id])

  end

  def edit
    @listing = Listing.find(params[:id])
  end


  def update
    @listing = Listing.find(params[:id])
    @listing.update(listings_params)
    @listing.user_id=current_user.id
    if @listing.save
      redirect_to listings_path
    else
      render 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id]).destroy
    redirect_to listings_path
  end

  def verify
    @listing=Listing.find(params[:id])

  end

  def user_listings
  end

  def search
    @listings = Listing.text_search(params[:search])
    render "index"
  end



  private

  def listings_params
    params.require(:listing).permit(:address, :price_per_day, :title_name, :listing_type , :bedrooms , :beds , :bathrooms,  :country ,:state , :city  , {images: []} )
  end

  def tags_params
    params.require('tags').permit(:tv , :kitchen , :pool, :smoking)
  end

  def set_listing
    @listing= Listing.find(params[:id])
  end

  def authorize_user
    if current_user.id != @listing.user_id && current_user.customer?

      redirect_to('listings_path', notice: "Sorry you dont have the authorization")

    end
  end
  def moderator_user
    @listing=Listing.find(params[:id])
    if current_user.superadmin?
      @listing.update(verified: true)
      flash[:notice] = "Successfuly verified"
      redirect_to listings_path

    elsif current_user.moderator?
      @listing.update(verified: true)
      flash[:notice] =  "Successfuly verified"
      redirect_to listings_path

    elsif current_user.customer?
      flash[:notice] = "Sorry you dont have the authorization"
      redirect_to listings_path

    end


  end


end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $("#exampleModalCenter").modal('show');
  });
</script>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  Start Hosting
</button>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Create Listing</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with model: @listing , local: true do |form| %>
          <div class="row">
            <div class="col-6">
              <%= form.text_field :title_name , label: "Title Name" %>
            </div>
            <div class="col-6">
              <%= form.text_field :listing_type , label: "Type" %>
            </div>
          </div>
          <br/>
          <div class = "row">
            <div class="col-6">
              <%= form.text_field :address , label: "Address"%></div>
            <div class="col-6">
              <%= form.text_field :price_per_day , label: "Price Per Day"%></div>
          </div>
          <br/>
          <div class = "row">
            <div class = "col-4">
              <%= form.text_field :bedrooms, label: "Number of Bedrooms" %></div>
            <div class = "col-4">
              <%= form.text_field :beds , label: "Number of Beds"%></div>
            <div class = "col-4">
              <%= form.text_field :bathrooms , label: "Number of Bathrooms"%></div>
          </div>
          <br/>
          <div class = "row">
            <div class = "col-4">
              <%= form.text_field :country , label: "Country"%></div>
            <div class = "col-4">
              <%= form.text_field :state , label: "State"%></div>
            <div class = "col-4">
              <%= form.text_field :city , label: "City"%></div>
          </div>
          <div class = "row">
            <div class = "col-6">
              <%= form.file_field :images , multiple: true  , label:"Image Preview"  %></div>
          </div>
          <br/>
        </div>
        <div class = "ml-3">
          <h3> Available amenitites: </h3>
          <br/>
          <div>
            <% ListingsController::TAGS.each do |tag| %>
              <%= form.label tag %>
              <%= check_box_tag "tags[#{tag}]",1 ,@listing.tags && @listing.tags.include?(tag) ? true : false %><br/>
            <% end %>
          </div>
        </div>
        <%= form.submit 'Submit Listing'%>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/listings/_listing.html.erb
<% if @listings.present?%>
  <%= form_with url: listings_path , class:"form-inline" ,method: :get do |form| %>
    <%= form.text_field :search , id:"keyup", class:"form-control mr-sm-2" , type:"search", placeholder: "Search" , list:"titles"%>
    <datalist id="titles">
    </datalist>
    <%= form.submit  class:"btn btn-outline-dark my-2 my-sm-0"  %>
  <% end %>
  <% form_with url: listings_path , class: "form-inline" , method: :get do |form| %>
    <%= form.text_field :min_max_price , class:"form-control mr-sm-2", placeholder: "Price" %>
  <% end %>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    More Filters
  </button>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Rooms and Beds</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class = "row">
            <div class = "col-4">
              <p>Number of Beds:</p>
            </div>
            <div class = "col-8">
              <div class="qty ml-auto">
                <%= form_with url: listings_path , class:"form-inline" ,id:'button', method: :get do |form| %>
                  <span class="minus bg-dark">-</span>
                  <!-- <input type="number" class="count" name="qty" value="1"> -->
                  <%= form.text_field :number ,class:"count" , value:"1" , placeholder: "Number" %>
                  <%= form.submit  class:"btn btn-outline-dark my-2 my-sm-0"  %>
                  <span class="plus bg-dark">+</span><br/>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>
      </div>
    </div>
  </div>
  <strong>
    <h1>All listings</h1>
  </strong>
  <br/>
  <% @listings.each do |listing|%>
    <div class="d-inline-block">
      <div class="card-deck">
        <div class="card text-white bg-dark text-center" style="width: 18rem; height: 33rem;">
          <div class="card-group">
            <img class="card-img-top" src="<%=listing.images.first%> " alt="Card image cap">
            <div class="card-body">
              <h5 class="card-header bg-transparent border-light"><%=listing.title_name%></h5>
              <% if listing.verified == true %>
                <br/>
                <img src = "1.png">
              <% end %>
              <br/>
              <p class="card-text"> Price/per night:
                $<%= listing.price_per_day %><br/>
                Bedrooms: 
                <%= listing.bedrooms %><br/>
                Address:
                <%= listing.address %></p>
              <%= link_to 'Show' , listing_path(listing.id) , class:'btn btn-primary btn-sm' %>
              <% if  current_user.superadmin? || current_user.id ==listing.user_id  %>
                <div class="card-footer bg-transparent border-dark">
                  <%= link_to 'Edit' , edit_listing_path(listing.id), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Delete' , listing_path(listing.id) , class: 'btn btn-primary btn-sm' , 
                method: :delete,
                data: { confirm: 'Are you sure?' }%>
                </div>
              <% end %>
              <% if !current_user.customer? %>
                <%= form_tag(verify_listing_path(listing.id)) do %>
                  <br/>
                  <%= submit_tag 'Verify', class: 'btn btn-primary btn-sm' %>
                  <p class="card-text"><small class="text-muted"><%=listing.created_at%></small></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</p>
<% elsif !@listings.present?%>
  <h1> No listings available with this current given search parameters</h1>
  <%= link_to 'Add Listing' , new_listing_path %>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $('#button').on('submit', function() {
      $('#exampleModal').modal('hide')
      $('body').removeClass('modal-open');
      $('.modal-backdrop').remove();
    });
  })
</script>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render "form" %>
<% link_to 'Back' , listings_path %>

app/views/listings/index.html.erb
<div id = "all" >
  <%= render "listing" %>
</div>

app/views/listings/index.js.erb
$('#all').html("<%=j render 'listing' %>");

app/views/listings/new.html.erb
<h1>Create New Listing</h1>
<%= render "form" %>

app/views/listings/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @listing.title_name %></h1>
  <p class="lead">Address:
    <%= @listing.address %><br/>
    Price/night:
    <%= @listing.price_per_day %><br/>
    Type:
    <%= @listing.listing_type %></p>
  <hr class="my-4">
  <p>Number of bedrooms:
    <%= @listing.bedrooms %><br/>
    Number of beds:
    <%= @listing.beds %><br/>
    Number of bathrooms:
    <%= @listing.bathrooms %></p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Book now' , new_listing_reservation_path(@listing) , class:"btn btn-primary btn-lg" %>
  </p>
</div>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 400px; margin: 0 auto">
  <div class="carousel-inner">
    <% @listing.images.each_with_index do |img , index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : nil %>">
        <%= image_tag (img.url), :class => "image" %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<hr/>
<%= link_to 'Back' , listings_path %>
<%= link_to 'Edit' , edit_listing_path(@listing.id) %>
<%= link_to 'Delete' , listing_path(@listing.id) ,
        method: :delete,
        data: { confirm: 'Are you sure?' }%>

app/views/listings/user_listings.html.erb
<% if current_user.listings.present?%>
  <h1> Your previous listings:</h1>
  <br/>
  <% current_user.listings.each do |listing|%>
    <div class="d-inline-block">
      <div class="card-deck">
        <div class="card text-white bg-dark text-center" style="width: 18rem; height: 33rem;">
          <div class="card-group">
            <img class="card-img-top" src="<%=listing.images.first%> " alt="Card image cap">
            <div class="card-body">
              <h5 class="card-header bg-transparent border-light"><%=listing.title_name%></h5>
              <% if listing.verified == true %>
                <br/>
                <img src = "1.png">
              <% end %>
              <br/>
              <p class="card-text"> Price/per night:
                $<%= listing.price_per_day %><br/>
                Bedrooms: 
                <%= listing.bedrooms %><br/>
                Address:
                <%= listing.address %></p>
              <%= link_to 'Show' , listing_path(listing.id) , class:'btn btn-primary btn-sm' %>
              <div class="card-footer bg-transparent border-dark">
                <%= link_to 'Edit' , edit_listing_path(listing.id), class: 'btn btn-primary btn-sm' %>
                <%= link_to 'Delete' , listing_path(listing.id) , class: 'btn btn-primary btn-sm' , 
                method: :delete,
                data: { confirm: 'Are you sure?' }%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% elsif !current_user.listings.present?%>
  <h1>You dont have any listings available</h1>
  <%= link_to 'Add Listing' , new_listing_path %>
<% end %>