config/routes.rb
Rails.application.routes.draw do
  get '/reservations/:id/braintree/new' => "braintree#new" , as:"new_braintree"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create , :show , :edit , :update] do

    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

    resources :reservations, only: [:index]

  end
  resources :listings do
    resources :reservations
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'users#index'
  get 'users/secret'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/listings/:id/user_listings" => "listings#user_listings" , as: "user_listings"

  post '/listings/:id/verify' => "listings#verify", as: "verify_listing"
  post '/reservations/:id/checkout' => "braintree#checkout", as: "checkout"
  post '/listings/search' => "listings#search" , as:"search"
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations , dependent: :destroy
  enum role: [:superadmin , :moderator , :customer]
  mount_uploader :image, ImageUploader



  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      first_name: auth_hash["info"]["name"],
      last_name: auth_hash["info"]["name"],


      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)

    )
    user.authentications << authentication
    return user
  end

  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end


end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login
  def index

  end
  def secret
  end
  def show
    @user = User.find(params[:id])
    @reservations = current_user.reservations
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @user.update(userss_params)


    if @user.save
      flash[:notice]= "Successfuly updated"
      redirect_to user_path
    else
      render 'edit'
    end
  end


  private

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    image = user_params.delete(:image)



    Clearance.configuration.user_model.new(user_params).tap do |user|

      user.email = email
      user.password = password
      user.first_name = first_name
      user.last_name = last_name
      user.image = image

    end
  end
  def userss_params

    params.require(:user).permit(:first_name, :last_name, :email , :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field col-5">
  <%= form.text_field :first_name, type: 'text' %>
  <div class="text-field">
    <%= form.text_field :last_name, type: 'text' %>
  </div>
  <div class="text-field">
    <%= form.text_field :email, type: 'email' %>
  </div>
  <div class="password-field">
    <%= form.password_field :password , label:"Password" %>
  </div>
  <div>
    <%= form.file_field :image, label:"Profile Picture" %>
  </div>

app/views/users/edit.html.erb
<%= bootstrap_form_with(model: @user , local: true) do |form| %>
  <div class="text-field">
    <%= form.text_field :first_name, type: 'text' %>
    <div class="text-field">
      <%= form.text_field :last_name, type: 'text' %>
    </div>
    <%= form.text_field :email, type: 'email' %>
  </div>
  <div>
    <%= form.file_field :image , label:"Update Profile Picture"%>
  </div>
  <%= form.submit%>
<% end %>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello <%= current_user.first_name %></h1>
  <p class="lead">This is SudanBnb, Sudans fully web developed web app Check out our homes and cheap prices </p>
  <p class="lead">
    <%= link_to 'Go to Listings' , listings_path , class: "btn btn-primary btn-lg"%>
  </p>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>
  <%= bootstrap_form_for (@user) do |form| %>
    <%= render partial: '/users/form', object: form %>
    <div class="submit-field">
      <%= form.submit %>
    </div>
    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/secret.html.erb
<h1>Top secret</h1>

app/views/users/show.erb
<h1> WELCOME <%=current_user.first_name %></h1>

<%= image_tag current_user.image_url(:thumb), :class => "profile mb-3"%><br/>
<%= link_to 'update profile' , edit_user_path(current_user.id) , :class => "btn btn-primary btn-sm"%>
<hr/>
<% if @reservations.present? %>
<h1>Previous Reservations </h1>
<% @reservations.each do |reservation| %>
<div class="d-inline-block">
      <div class="card-deck">
        <div class="card text-white bg-dark text-center" style="width: 18rem; height: 33rem;">
          <div class="card-group">
            <img class="card-img-top" src="<%=reservation.listing.images.first%> " alt="Card image cap">
            <div class="card-body">
              <h5 class="card-header bg-transparent border-light"><%=reservation.listing.title_name%></h5>
              <% if reservation.listing.verified == true %>
                <br/>
                <img src = "1.png">
              <% end %>
              <br/>
              <p class = "card-text">hoster name:</p>
					<%= reservation.user.first_name%>
				<p class = "card-text">Listing name:</p>
					<%= reservation.listing.title_name %>
				<p class = "card-text">Start Date:</p>
					<%= reservation.start_date %><br/>
				<p class = "card-text">End Date</p>
					<%= reservation.end_date %><br/>
				<p class = "card-text">Price of Stay</p>
					<%= reservation.total_price %><br/>

             
                <div class="card-footer bg-transparent border-dark">
              <%= link_to 'Show' , listing_path(reservation.listing.id) , class:'btn btn-primary btn-sm' %>
                  
                </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% elsif !@reservations.present? %>
    <p> You dont have  any previous reservations.Want to book now and enjoy our exquisite service?</p><br/>
    <%= link_to 'Listings' , listings_path , class:"btn btn-primary" %>
    <% end%>