config/routes.rb
Rails.application.routes.draw do
  get '/reservations/:id/braintree/new' => "braintree#new" , as:"new_braintree"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create , :show , :edit , :update] do

    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

    resources :reservations, only: [:index]

  end
  resources :listings do
    resources :reservations
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'users#index'
  get 'users/secret'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/listings/:id/user_listings" => "listings#user_listings" , as: "user_listings"

  post '/listings/:id/verify' => "listings#verify", as: "verify_listing"
  post '/reservations/:id/checkout' => "braintree#checkout", as: "checkout"
  post '/listings/search' => "listings#search" , as:"search"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SudanBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- Load the Client component. -->
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to image_tag('airbnb.png', class: 'airbnb'),root_url%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">SS
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <% if signed_in? %>
                  <li class="nav-item">
                    <%= link_to 'My profile' , user_path(current_user.id) , class:'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'My listings' , user_listings_path(current_user.id) , class:'nav-link'  %>
                  </li>
                  <li class = "nav-item">
                    <%= link_to "Start Hosting", new_listing_path , class:'nav-link' %>
                  </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                  <!-- <form class="form-inline" action = "listings/search"  > -->
                  <!-- <li> -->
                  <!--  <input  class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                  </form> -->
                  <li>
                    <%= form_with url: search_path , class:"form-inline" ,local:true do |form| %>
                      <%= form.text_field :search , class:"form-control mr-sm-2", type:"search", placeholder: "Search" %>
                      <%= form.submit  class:"btn btn-outline-dark my-2 my-sm-0"  %>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Logout' , sign_out_path , class:'nav-link' , :method => :delete %>
                  </li>
                </ul>
              <% else %>
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <strong><%= link_to 'Sign up' , sign_up_path , class:'nav-link'  %></strong>
                  </li>
                </ul>
                <!--  <form class="form-inline" action = "listings/search" >
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                </form> -->
              <% end %>
            </div>
          </div>
        </nav>
      </div>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>"><%= value %></div>
        <% end %>
      </div>
      <hr/>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>